name: flutter_teleheal
description: A new flutter module project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  reactive_forms: ^11.0.1
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/


  module:
    androidX: true
    androidPackage: com.example.flutter_teleheal
    iosBundleIdentifier: com.example.flutterTeleheal
